### ISSUE TITLE
Need instructions for how to create Firestore data source

### ISSUE THREAD

**Issue by jhight** [AntonShuvaev/intellij-firebase-firestore#1]
I installed and enabled the plugin, but I don't see any firestore option in the data source menu. Can you please add instructions for how to set up a firestore data source?

**Comment by jhight** [comment]
For future viewers, the plugin adds a firebase panel menu on the side, from which you can add a firebase connection. I would still recommend adding instructions.

**Comment by AntonShuvaev** [comment]
I've added instructions on how to create a connection in the 'Getting Started' section of the plugin page at https://plugins.jetbrains.com/plugin/23609-firebase-firestore

**Comment by jimcornmell** [comment]
Might be a good idea to include an example.  For example I can connect to the database using java/kotlin and the cloud webpage and gcloud command line.  Just get this error from the plugin.....

![image](https://github.com/user-attachments/assets/c088b98b-cd9e-42fa-a98a-6310d115882d)

Using same json file etc.
